import React from "react";
import ReactDOM from "react-dom/client";

const root = ReactDOM.createRoot(document.getElementById("root"));

const Header = () => {
  return (
    <div className="header">
      <div className="logo-container">
        <img
          className="logo"
          src= {require("./Images/foodtastic.png") }
        />
      </div>
      <div className="nav-items">
        <ul>
          <li>Home</li>
          <li>About Us</li>
          <li>Contact Us</li>
          <li>Cart</li>
        </ul>
      </div>
    </div>
  );
};

const resList = [
  {
    data: {
      type: "F",
      id: "56497",
      name: "Maravanthe",
      uuid: "d7adcf92-5114-47e0-bf33-d2ba565e69f6",
      city: "1",
      area: "Indiranagar",
      totalRatingsString: "",
      cloudinaryImageId: "v06l1tgc4eay4e43wwxu",
      cuisines: ["Seafood"],
      tags: [],
      costForTwo: 80000,
      costForTwoString: "₹800 FOR TWO",
      deliveryTime: 40,
      minDeliveryTime: 40,
      maxDeliveryTime: 40,
      slaString: "40 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "maravanthe-indiranagar-indiranagar",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "CMH Road",
      parentId: 7368,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: "",
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 5800,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5800,
        message: "",
        title: "Delivery Charge",
        amount: "5800",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7518243~p=1~eid=00000189-6ce7-fd31-1c21-ad99008a0107~srvts=1689749290289~80426",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "6.1 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=56497&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 40,
        minDeliveryTime: 40,
        maxDeliveryTime: 40,
        lastMileTravel: 0,
        lastMileDistance: 6.1,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.2",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    data: {
      type: "F",
      id: "1050",
      name: "Nagarjuna Chimney",
      uuid: "d4e2272f-90f2-4dd0-9bec-258eee0e692e",
      city: "1",
      area: "Jaya Nagar",
      totalRatingsString: "",
      cloudinaryImageId: "hirj3b66f3uphbdinhev",
      cuisines: [
        "Seafood",
        "Andhra",
        "Biryani",
        "South Indian",
        "Desserts",
        "Beverages",
      ],
      tags: [],
      costForTwo: 80000,
      costForTwoString: "₹800 FOR TWO",
      deliveryTime: 37,
      minDeliveryTime: 37,
      maxDeliveryTime: 37,
      slaString: "37 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "nagarjuna-chimney-3rd-block-jayanagar",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "3rd Block",
      parentId: 143166,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 5800,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5800,
        message: "",
        title: "Delivery Charge",
        amount: "5800",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7300097~p=2~eid=00000189-6ce7-fd31-1c21-ad9a008a0230~srvts=1689749290289~80426",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "6.1 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=1050&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        lastMileTravel: 0,
        lastMileDistance: 6.1,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.3",
      totalRatings: 0,
      new: false,
    },
  },
  {
    data: {
      type: "F",
      id: "2408",
      name: "Suchi Ruchi",
      uuid: "d892cc0b-bb7e-4192-8455-7ff915c5930f",
      city: "1",
      area: "Malleshwaram",
      totalRatingsString: "",
      cloudinaryImageId: "atge8pxvpuh5wj0rxcs2",
      cuisines: ["South Indian", "Chinese", "Chaat", "North Indian", "Snacks"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 32,
      minDeliveryTime: 32,
      maxDeliveryTime: 32,
      slaString: "32 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "shuchi-ruchi-malleshwaram",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "10th Cross Road",
      parentId: 21101,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: "",
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 5000,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5000,
        message: "",
        title: "Delivery Charge",
        amount: "5000",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7522301~p=4~eid=00000189-6ce7-fd31-1c21-ad9c008a0414~srvts=1689749290289~80426",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "5.9 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=2408&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        lastMileTravel: 0,
        lastMileDistance: 5.9,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.0",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },

  {
    data: {
      type: "F",
      id: "307554",
      name: "Bangalore Thindies",
      uuid: "ceae074e-e93a-47f7-9665-b6c406e15c11",
      city: "1",
      area: "Shivaji Nagar",
      totalRatingsString: "",
      cloudinaryImageId: "gmusbb8jn3ocox01hnc7",
      cuisines: ["South Indian"],
      tags: [],
      costForTwo: 8000,
      costForTwoString: "₹80 FOR TWO",
      deliveryTime: 23,
      minDeliveryTime: 23,
      maxDeliveryTime: 23,
      slaString: "23 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "bangalore-thindies-central-bangalore-central-bangalore",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "Infantry Road",
      parentId: 20090,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: "",
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 2500,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2500,
        message: "",
        title: "Delivery Charge",
        amount: "2500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7521495~p=5~eid=00000189-6ce7-fd31-1c21-ad9d008a0503~srvts=1689749290289~80426",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.2 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=307554&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        lastMileTravel: 0,
        lastMileDistance: 2.2,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.1",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    data: {
      type: "F",
      id: "568186",
      name: "Millet Express",
      uuid: "1982d968-1e73-4418-a9dc-9784f535be74",
      city: "1",
      area: "Indiranagar",
      totalRatingsString: "",
      cloudinaryImageId: "f89f83a650ad14380ffa50fccd9e2ac3",
      cuisines: [
        "Healthy Food",
        "South Indian",
        "North Indian",
        "Biryani",
        "Chinese",
        "Beverages",
      ],
      tags: [],
      costForTwo: 15000,
      costForTwoString: "₹150 FOR TWO",
      deliveryTime: 32,
      minDeliveryTime: 32,
      maxDeliveryTime: 32,
      slaString: "32 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "millet-express-indiranagar-indiranagar",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "Appareddy Palya",
      parentId: 10639,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: "",
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 5000,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5000,
        message: "",
        title: "Delivery Charge",
        amount: "5000",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7288528~p=6~eid=00000189-6ce7-fd31-1c21-ad9e008a0660~srvts=1689749290289~80426",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [
          {
            iconId: "guiltfree/GF_Logo_android_3x",
            description: "",
            shortDescription: "brand",
            fontColor: "#7E808C",
          },
        ],
      },
      lastMileTravelString: "5.9 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=568186&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        lastMileTravel: 0,
        lastMileDistance: 5.9,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.3",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    data: {
      type: "F",
      id: "121603",
      name: "Kannur Food Point",
      uuid: "51983905-e698-4e31-b0d7-e376eca56320",
      city: "1",
      area: "Tavarekere",
      totalRatingsString: "",
      cloudinaryImageId: "bmwn4n4bn6n1tcpc8x2h",
      cuisines: ["Kerala", "Chinese"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 31,
      minDeliveryTime: 31,
      maxDeliveryTime: 31,
      slaString: "31 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "kannur-food-point-btm",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "SG Palya",
      parentId: 20974,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 5800,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5800,
        message: "",
        title: "Delivery Charge",
        amount: "5800",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "6.7 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=121603&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        lastMileTravel: 0,
        lastMileDistance: 6.7,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.9",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },

  {
    data: {
      type: "F",
      id: "56428",
      name: "Puliyogare Point",
      uuid: "49970568-119d-436c-9dad-042d9c07c7ff",
      city: "1",
      area: "Basavanagudi",
      totalRatingsString: "",
      cloudinaryImageId: "wet9zrjusmdtkk16jlrz",
      cuisines: ["South Indian"],
      tags: [],
      costForTwo: 15000,
      costForTwoString: "₹150 FOR TWO",
      deliveryTime: 25,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      slaString: "25 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "puliyogare-point-basavanagudi-basavanagudi",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "N.R Colony",
      parentId: 8409,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: "",
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 3500,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "4.9 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=56428&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        lastMileTravel: 0,
        lastMileDistance: 4.9,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.5",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    data: {
      type: "F",
      id: "4046",
      name: "Sri Udupi Park",
      uuid: "5b811b78-56d2-4d80-9681-7630cb3904c6",
      city: "1",
      area: "Residency Road",
      totalRatingsString: "",
      cloudinaryImageId: "tfbnpd65irvhp9iwhbtk",
      cuisines: [
        "North Indian",
        "South Indian",
        "Chinese",
        "Chaat",
        "Beverages",
      ],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 30,
      minDeliveryTime: 30,
      maxDeliveryTime: 30,
      slaString: "30 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "veg-feast-central-bangalore",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "Galaxy Mall",
      parentId: 4284,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: "",
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 2500,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2500,
        message: "",
        title: "Delivery Charge",
        amount: "2500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.3 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=4046&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        lastMileTravel: 0,
        lastMileDistance: 2.3,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.4",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    data: {
      type: "F",
      id: "34301",
      name: "Sri Udupi Park (100ft Road)",
      uuid: "82e5a42b-6a2d-45c7-a096-320333bd6c4e",
      city: "1",
      area: "Indiranagar",
      totalRatingsString: "",
      cloudinaryImageId: "jxp8y1chnqljwqylpkov",
      cuisines: [
        "South Indian",
        "North Indian",
        "Chaat",
        "Beverages",
        "Chinese",
      ],
      tags: [],
      costForTwo: 10000,
      costForTwoString: "₹100 FOR TWO",
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: "35 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "sri-udupi-park-indiranagar-indiranagar",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "Defence Colony",
      parentId: 194697,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 5800,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5800,
        message: "",
        title: "Delivery Charge",
        amount: "5800",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "6.4 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=34301&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 0,
        lastMileDistance: 6.4,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    data: {
      type: "F",
      id: "205813",
      name: "Paakashala",
      uuid: "e1eadef1-651d-4216-bd6e-ac63aa13fe25",
      city: "1",
      area: "MG Road",
      totalRatingsString: "",
      cloudinaryImageId: "thkhqrsskc5745ztfz2v",
      cuisines: ["South Indian", "North Indian", "Chinese"],
      tags: [],
      costForTwo: 50000,
      costForTwoString: "₹500 FOR TWO",
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      slaString: "26 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "paakashala-central-bangalore-central-bangalore",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "MG Road",
      parentId: 6959,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: "",
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 2500,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2500,
        message: "",
        title: "Delivery Charge",
        amount: "2500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.2 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=205813&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        lastMileTravel: 0,
        lastMileDistance: 2.2,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },

  {
    data: {
      type: "F",
      id: "96527",
      name: "Vijayalakshmi",
      uuid: "832cd579-956f-4480-8cf8-42af4fea46a0",
      city: "1",
      area: "Basavanagudi",
      totalRatingsString: "",
      cloudinaryImageId: "r94u50lcikbaqulaofdi",
      cuisines: ["South Indian", "North Indian", "Chinese"],
      tags: [],
      costForTwo: 15000,
      costForTwoString: "₹150 FOR TWO",
      deliveryTime: 31,
      minDeliveryTime: 31,
      maxDeliveryTime: 31,
      slaString: "31 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "vijayalakshmi-basavanagudi",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "Bull Temple Rd",
      parentId: 20982,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: "",
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 5000,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5000,
        message: "",
        title: "Delivery Charge",
        amount: "5000",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "5 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=96527&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        lastMileTravel: 0,
        lastMileDistance: 5,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },

  {
    data: {
      type: "F",
      id: "12808",
      name: "A2B - Adyar Ananda Bhavan",
      uuid: "11b01c69-d5f5-47cd-a7b6-089138b8267f",
      city: "1",
      area: "Shanti Nagar",
      totalRatingsString: "",
      cloudinaryImageId: "pdod4o1em9potwsd22rs",
      cuisines: ["South Indian", "North Indian", "Sweets", "Chinese"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      slaString: "28 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "a2b-veg-cbd-central-bangalore",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "Wilson Garden",
      parentId: 22,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: "",
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 3500,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=12808&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        lastMileTravel: 0,
        lastMileDistance: 3,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.4",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    data: {
      type: "F",
      id: "58197",
      name: "Shanti Sagar",
      uuid: "c53b677e-5442-4fb8-b237-b9619a42ad36",
      city: "1",
      area: "Ulsoor",
      totalRatingsString: "",
      cloudinaryImageId: "ddlewhiegjaigcxnp5tr",
      cuisines: ["South Indian", "North Indian", "Chinese"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 39,
      minDeliveryTime: 39,
      maxDeliveryTime: 39,
      slaString: "39 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "shanti-sagar-ulsoor-central-bangalore",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "Tank Road",
      parentId: 20012,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: "",
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 3700,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3700,
        message: "",
        title: "Delivery Charge",
        amount: "3700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7521707~p=7~eid=00000189-6e9a-cc0c-1ea8-769800e9076c~srvts=1689777785868~80426",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "4.6 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=58197&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        lastMileTravel: 0,
        lastMileDistance: 4.6,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.3",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    data: {
      type: "F",
      id: "1216031",
      name: "Kannur Food Point",
      uuid: "51983905-e698-4e31-b0d7-e376eca56320",
      city: "1",
      area: "Tavarekere",
      totalRatingsString: "",
      cloudinaryImageId: "bmwn4n4bn6n1tcpc8x2h",
      cuisines: ["Kerala", "Chinese"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: "35 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "kannur-food-point-btm",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "SG Palya",
      parentId: 20974,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 6000,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 6000,
        message: "",
        title: "Delivery Charge",
        amount: "6000",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "6.7 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=121603&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 0,
        lastMileDistance: 6.7,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.9",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    data: {
      type: "F",
      id: "40461",
      name: "Sri Udupi Park",
      uuid: "5b811b78-56d2-4d80-9681-7630cb3904c6",
      city: "1",
      area: "Residency Road",
      totalRatingsString: "",
      cloudinaryImageId: "tfbnpd65irvhp9iwhbtk",
      cuisines: [
        "North Indian",
        "South Indian",
        "Chinese",
        "Chaat",
        "Beverages",
      ],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 30,
      minDeliveryTime: 30,
      maxDeliveryTime: 30,
      slaString: "30 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "veg-feast-central-bangalore",
        city: "Bangalore",
      },
      cityState: "1",
      address: "",
      locality: "Galaxy Mall",
      parentId: 4284,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: "",
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 2700,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.3 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=4046&source=collection&query=Dosa",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        lastMileTravel: 0,
        lastMileDistance: 2.3,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.4",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    data: {
      id: "366266",
      name: "Domino's Pizza",
      cloudinaryImageId: "okqkedt8ccz6e33vv2mp",
      locality: "Sector-2A",
      areaName: "Bidhan Nagar",
      costForTwo: 40000,
      deliveryTime: 25,
      cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
      avgRating: 4.1,
      feeDetails: {
        restaurantId: "366266",
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 1900,
          },
          {
            name: "BASE_TIME",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
          },
        ],
        totalFee: 1900,
      },
      parentId: "2456",
      avgRatingString: "4.1",
      totalRatingsString: "500+",
      sla: {
        deliveryTime: 25,
        serviceability: "SERVICEABLE",
        slaString: "25 mins",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2023-07-19 23:57:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹999",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    },
    analytics: {},
  },
];

const ResturantCard = (props) => {
  const { resData } = props;
  const {
    name,
    cuisines,
    avgRating,
    deliveryTime,
    costForTwo,
    cloudinaryImageId,
  } = resData?.data;
  return (
    <div className="res-cards">
      <div className="card">
        <img
          src={
            "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/" +
            cloudinaryImageId
          }
        />
        <p id="name">{name}</p>
        <p id="cuisines">{cuisines.join(", ")}</p>

        <div className="res-details">
          <ul>
            <li id="rating">{avgRating} Stars</li>
            <li> {deliveryTime} MINS</li>
            <li>Rs:{costForTwo / 100} FOR TWO</li>
          </ul>
        </div>
      </div>
    </div>
  );
};

const Body = () => {
  return (
    <div className="body-container">
      <div className="search">Search</div>
      <div className="res-container">
        {/* Resturant Cards */}
        {resList.map((resturant) => (
          <ResturantCard key={resturant.data.id} resData={resturant} />
        ))}
      </div>
    </div>
  );
};

const AppLayout = () => {
  return (
    <div className="app">
      <Header />
      <Body />
    </div>
  );
};

root.render(<AppLayout />);
